#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width  4
bspc config window_gap    9
bspc config top_padding   20

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer   true

bspc config focused_border_color  "#89DCEB"
bspc config normal_border_color   "#575268"
bspc config active_border_color   "#f5e0dc"
# bspc config presel_feedback_color "#"

# fix pointer
xsetroot -cursor_name left_ptr

bspc config pointer_modifier              mod4
bspc config pointer_action1               move
bspc config pointer_action2               resize_side
bspc config pointer_action3               resize_corner



#                                 ╭─────────────╮
#                                 │ bspwm rules │
#                                 ╰─────────────╯

bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a scpad sticky=on state=floating hidden=on
bspc rule -a *:*:Picture-in-Picture state=floating
bspc rule -a *:Password:Password state=floating
bspc rule -a feh state=floating
bspc rule -a calendar state=floating hidden=on
bspc rule -a wifi-float state=floating hidden=on
bspc rule -a dmenu stick=on state=floating center=on rectangle=176x625+0+0
bspc rule -a fetch border=off state=floating rectangle=340x240+36+115

#                               ╭─────────────────╮
#                               │ bspwm autostart │
#                               ╰─────────────────╯

# killall -9 picom sxhkd dunst

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
numlockx &
mpd &
xautolock -time 7 -locker "systemctl hybrid-sleep" &
xwallpaper --center ~/.local/share/background.png &
libinput-gestures-setup start &
~/.config/polybar/launch.sh &
sxhkd &
whoogle-search --port 9051 &
dunst &
# feh --bg-scale ~/.config/utils/wallpaper.png &
