#!/bin/bash

# this script is for taking a screenshot of a particular area

rm -f /tmp/temp_a.png
rm -f /tmp/temp_a-thumb.png
rm -f /tmp/output.txt
scrot -ps "/tmp/temp_a.png" -t 5
tesseract -l eng /tmp/temp_a.png /tmp/output
cat /tmp/output.txt | xclip -selection clipboard
mkdir -p ~/Pictures/Screenshots/"$(date +%m-%Y)"
cp /tmp/temp_a.png ~/Pictures/Screenshots/"$(date +%m-%Y)"/"Screenshot_$(date +%T_%d-%m-%Y).png"
dunstify -I /tmp/temp_a-thumb.png "Screenshot taken."
